name: Caddy

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/caddy.yml"
      - "caddy/**"
  workflow_dispatch: {}

env:
  IMAGE_NAME: notnotjosh/caddy
  PLATFORMS: linux/amd64

jobs:
  docker-proxy:
    name: Build and Publish
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Read Version
        id: read_version
        run: |
          READ_VERSION=`cat ./caddy/Dockerfile | grep 'ARG CADDY_VERSION' | sed -nre 's/^[^0-9]*(([0-9]+\.)*[0-9]+).*/\1/p'`
          echo "VERSION_TAG=$READ_VERSION" >> "$GITHUB_ENV"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish to container registry
        uses: docker/build-push-action@v5
        with:
          context: ./caddy
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.VERSION_TAG }}
            ${{ env.IMAGE_NAME }}:latest
          platforms: ${{ env.PLATFORMS }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
